# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountrySearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 5.0.0.beta.1'
    pod 'SwiftyJSON'
    pod 'RealmSwift'
    pod 'PocketSVG'
    
    
  # Pods for CountrySearch

  target 'CountrySearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountrySearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
